1. Display all the customers who live in Delhi.
2. Find the average rating of all the restaurants in Mumbai.
3. List all the customers who have placed at least one order.
4. Display the total number of orders placed by each customer.
5. Find the total revenue generated by each restaurant.
6. Find the top 5 restaurants with the highest average rating.
7. Display all customers who have never placed an order.
8. Find the number of orders placed by each customer in Mumbai.
9. Display all the orders placed in the last 30 days.
10. List all delivery partners who have completed more than 1 delivery.
11. Find the customers who have placed orders on exactly 3 different days.
12. Find the delivery partner who has worked with the most different customers.
13. Identify customers who are from the same city and have placed orders at the same restaurants but on different dates.